language: java
jdk:
  - oraclejdk8
  
install:
  - chmod +x ./mvnw
  - ./mvnw install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
script:
  - ./mvnw clean compile

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: airflights-isa

